
var m_count = 0;
m_items = new Array(
"<h3>ti.catalog.c6000</h3>",
"<h5>Arctic</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer0   </td><td> 0x4802c000         </td><td> 4         </td><td> 48         </td></tr>",
 "</table>",
"<h5>DRA7XX</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4ae18000         </td><td> 14         </td><td> 63         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48032000         </td><td> 15         </td><td> 64         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 14         </td><td> 65         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 15         </td><td> 66         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48820000         </td><td> 14         </td><td> 67         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48822000         </td><td> 15         </td><td> 68         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x48824000         </td><td> 14         </td><td> 69         </td></tr>",
   "<tr><td> 7        </td><td> GPTimer8   </td><td> 0x48826000         </td><td> 15         </td><td> 70         </td></tr>",
   "<tr><td> 8        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 14         </td><td> 71         </td></tr>",
   "<tr><td> 9        </td><td> GPTimer10   </td><td> 0x48086000         </td><td> 15         </td><td> 72         </td></tr>",
   "<tr><td> 10        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 14         </td><td> 73         </td></tr>",
   "<tr><td> 11        </td><td> GPTimer12   </td><td> 0x4ae20000         </td><td> -1         </td><td> 75         </td></tr>",
   "<tr><td> 12        </td><td> GPTimer13   </td><td> 0x48828000         </td><td> -1         </td><td> 76         </td></tr>",
   "<tr><td> 13        </td><td> GPTimer14   </td><td> 0x4882a000         </td><td> -1         </td><td> 77         </td></tr>",
   "<tr><td> 14        </td><td> GPTimer15   </td><td> 0x4882c000         </td><td> -1         </td><td> 78         </td></tr>",
   "<tr><td> 15        </td><td> GPTimer16   </td><td> 0x4882e000         </td><td> -1         </td><td> 81         </td></tr>",
 "</table>",
"<h5>OMAP4430</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer5   </td><td> 0x1d38000         </td><td> 14         </td><td> 51         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer6   </td><td> 0x1d3a000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer7   </td><td> 0x1d3c000         </td><td> 4         </td><td> 53         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer8   </td><td> 0x1d3e000         </td><td> 5         </td><td> 54         </td></tr>",
 "</table>",
"<h5>OMAP5430</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer5   </td><td> 0x1d38000         </td><td> 14         </td><td> 51         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer6   </td><td> 0x1d3a000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer7   </td><td> 0x1d3c000         </td><td> 4         </td><td> 53         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer8   </td><td> 0x1d3e000         </td><td> 5         </td><td> 54         </td></tr>",
 "</table>",
"<h5>TMS320C6A8149</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer3   </td><td> 0x8042000         </td><td> 14         </td><td> 51         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer4   </td><td> 0x8044000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer5   </td><td> 0x8046000         </td><td> 11         </td><td> 53         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer6   </td><td> 0x8048000         </td><td> 12         </td><td> 54         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer7   </td><td> 0x804a000         </td><td> 13         </td><td> 55         </td></tr>",
 "</table>",
"<h5>TMS320C6A8168</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x8044000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x8046000         </td><td> 11         </td><td> 53         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x8048000         </td><td> 12         </td><td> 54         </td></tr>",
 "</table>",
"<h5>TMS320CDM740</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x8044000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x8046000         </td><td> 11         </td><td> 53         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x8048000         </td><td> 12         </td><td> 54         </td></tr>",
 "</table>",
"<h5>TMS320DM8148</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer3   </td><td> 0x8042000         </td><td> 14         </td><td> 51         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer4   </td><td> 0x8044000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer5   </td><td> 0x8046000         </td><td> 11         </td><td> 53         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer6   </td><td> 0x8048000         </td><td> 12         </td><td> 54         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer7   </td><td> 0x804a000         </td><td> 13         </td><td> 55         </td></tr>",
 "</table>",
"<h5>TMS320DM8168</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x8044000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x8046000         </td><td> 11         </td><td> 53         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x8048000         </td><td> 12         </td><td> 54         </td></tr>",
 "</table>",
"<h5>TMS320TI811X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer3   </td><td> 0x8042000         </td><td> 14         </td><td> 51         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer4   </td><td> 0x8044000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer5   </td><td> 0x8046000         </td><td> 11         </td><td> 53         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer6   </td><td> 0x8048000         </td><td> 12         </td><td> 54         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer7   </td><td> 0x804a000         </td><td> 13         </td><td> 55         </td></tr>",
 "</table>",
"<h5>TMS320TI814X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer3   </td><td> 0x8042000         </td><td> 14         </td><td> 51         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer4   </td><td> 0x8044000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer5   </td><td> 0x8046000         </td><td> 11         </td><td> 53         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer6   </td><td> 0x8048000         </td><td> 12         </td><td> 54         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer7   </td><td> 0x804a000         </td><td> 13         </td><td> 55         </td></tr>",
 "</table>",
"<h5>TMS320TI816X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x8044000         </td><td> 15         </td><td> 52         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x8046000         </td><td> 11         </td><td> 53         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x8048000         </td><td> 12         </td><td> 54         </td></tr>",
 "</table>",
"<h5>Vayu</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4ae18000         </td><td> 14         </td><td> 63         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48032000         </td><td> 15         </td><td> 64         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 14         </td><td> 65         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 15         </td><td> 66         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48820000         </td><td> 14         </td><td> 67         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48822000         </td><td> 15         </td><td> 68         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x48824000         </td><td> 14         </td><td> 69         </td></tr>",
   "<tr><td> 7        </td><td> GPTimer8   </td><td> 0x48826000         </td><td> 15         </td><td> 70         </td></tr>",
   "<tr><td> 8        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 14         </td><td> 71         </td></tr>",
   "<tr><td> 9        </td><td> GPTimer10   </td><td> 0x48086000         </td><td> 15         </td><td> 72         </td></tr>",
   "<tr><td> 10        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 14         </td><td> 73         </td></tr>",
   "<tr><td> 11        </td><td> GPTimer12   </td><td> 0x4ae20000         </td><td> -1         </td><td> 75         </td></tr>",
   "<tr><td> 12        </td><td> GPTimer13   </td><td> 0x48828000         </td><td> -1         </td><td> 76         </td></tr>",
   "<tr><td> 13        </td><td> GPTimer14   </td><td> 0x4882a000         </td><td> -1         </td><td> 77         </td></tr>",
   "<tr><td> 14        </td><td> GPTimer15   </td><td> 0x4882c000         </td><td> -1         </td><td> 78         </td></tr>",
   "<tr><td> 15        </td><td> GPTimer16   </td><td> 0x4882e000         </td><td> -1         </td><td> 81         </td></tr>",
 "</table>",
"<h3>ti.catalog.arm</h3>",
"<h5>TMS320CDM740</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
 "</table>",
"<h3>ti.catalog.arm.cortexa8</h3>",
"<h5>AM3359</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> DMTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> DMTimer3   </td><td> 0x48042000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> DMTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> DMTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> DMTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> DMTimer7   </td><td> 0x4804a000         </td><td> 95         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>AM335X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> DMTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> DMTimer3   </td><td> 0x48042000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> DMTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> DMTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> DMTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> DMTimer7   </td><td> 0x4804a000         </td><td> 95         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320C6A8149</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4802e000         </td><td> 67         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48042000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 95         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320C6A8168</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4802e000         </td><td> 67         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320DM8148</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4802e000         </td><td> 67         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48042000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 95         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320DM8168</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4802e000         </td><td> 67         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320TI811X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4802e000         </td><td> 67         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48042000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 95         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320TI813X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4802e000         </td><td> 67         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48042000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 95         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320TI814X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4802e000         </td><td> 67         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48042000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 95         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320TI816X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4802e000         </td><td> 67         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48040000         </td><td> 68         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 92         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 93         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 94         </td><td> Not used         </td></tr>",
 "</table>",
"<h3>ti.catalog.arm.cortexa9</h3>",
"<h5>OMAP4430</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 71         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 72         </td><td> Not used         </td></tr>",
 "</table>",
"<h3>ti.catalog.arm.cortexa15</h3>",
"<h5>DRA7XX</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4ae18000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48032000         </td><td> 70         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 71         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 72         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48820000         </td><td> 73         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48822000         </td><td> 74         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x48824000         </td><td> 75         </td><td> Not used         </td></tr>",
   "<tr><td> 7        </td><td> GPTimer8   </td><td> 0x48826000         </td><td> 76         </td><td> Not used         </td></tr>",
   "<tr><td> 8        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 77         </td><td> Not used         </td></tr>",
   "<tr><td> 9        </td><td> GPTimer10   </td><td> 0x48086000         </td><td> 78         </td><td> Not used         </td></tr>",
   "<tr><td> 10        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 79         </td><td> Not used         </td></tr>",
   "<tr><td> 11        </td><td> GPTimer12   </td><td> 0x4ae20000         </td><td> 127         </td><td> Not used         </td></tr>",
   "<tr><td> 12        </td><td> GPTimer13   </td><td> 0x48828000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 13        </td><td> GPTimer14   </td><td> 0x4882a000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 14        </td><td> GPTimer15   </td><td> 0x4882c000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 15        </td><td> GPTimer16   </td><td> 0x4882e000         </td><td> -1         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>OMAP5430</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer2   </td><td> 0x48032000         </td><td> 70         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer10   </td><td> 0x48086000         </td><td> 78         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>Vayu</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4ae18000         </td><td> 69         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48032000         </td><td> 70         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 71         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 72         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48820000         </td><td> 73         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48822000         </td><td> 74         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x48824000         </td><td> 75         </td><td> Not used         </td></tr>",
   "<tr><td> 7        </td><td> GPTimer8   </td><td> 0x48826000         </td><td> 76         </td><td> Not used         </td></tr>",
   "<tr><td> 8        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 77         </td><td> Not used         </td></tr>",
   "<tr><td> 9        </td><td> GPTimer10   </td><td> 0x48086000         </td><td> 78         </td><td> Not used         </td></tr>",
   "<tr><td> 10        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 79         </td><td> Not used         </td></tr>",
   "<tr><td> 11        </td><td> GPTimer12   </td><td> 0x4ae20000         </td><td> 127         </td><td> Not used         </td></tr>",
   "<tr><td> 12        </td><td> GPTimer13   </td><td> 0x48828000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 13        </td><td> GPTimer14   </td><td> 0x4882a000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 14        </td><td> GPTimer15   </td><td> 0x4882c000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 15        </td><td> GPTimer16   </td><td> 0x4882e000         </td><td> -1         </td><td> Not used         </td></tr>",
 "</table>",
"<h3>ti.catalog.arm.cortexm3</h3>",
"<h5>OMAP4430</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 53         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 54         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 55         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 56         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>OMAP5430</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 53         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 54         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 55         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 56         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320C6A8149</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 31         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320C6A8168</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320DM8148</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 31         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320DM8168</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320TI811X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 31         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320TI813X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 31         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320TI814X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer7   </td><td> 0x4804a000         </td><td> 31         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>TMS320TI816X</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer4   </td><td> 0x48044000         </td><td> 28         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer5   </td><td> 0x48046000         </td><td> 29         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer6   </td><td> 0x48048000         </td><td> 30         </td><td> Not used         </td></tr>",
 "</table>",
"<h3>ti.catalog.arm.cortexm4</h3>",
"<h5>DRA7XX</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4ae18000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48032000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 53         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 54         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48820000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48822000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x48824000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 7        </td><td> GPTimer8   </td><td> 0x48826000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 8        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 55         </td><td> Not used         </td></tr>",
   "<tr><td> 9        </td><td> GPTimer10   </td><td> 0x48086000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 10        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 56         </td><td> Not used         </td></tr>",
   "<tr><td> 11        </td><td> GPTimer12   </td><td> 0x4ae20000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 12        </td><td> GPTimer13   </td><td> 0x48828000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 13        </td><td> GPTimer14   </td><td> 0x4882a000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 14        </td><td> GPTimer15   </td><td> 0x4882c000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 15        </td><td> GPTimer16   </td><td> 0x4882e000         </td><td> -1         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>OMAP5430</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 53         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 54         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 55         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 56         </td><td> Not used         </td></tr>",
 "</table>",
"<h5>Vayu</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th><th> Timer Interrupt Number </th><th> Timer Event Id </th></tr>",
   "<tr><td> 0        </td><td> GPTimer1   </td><td> 0x4ae18000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 1        </td><td> GPTimer2   </td><td> 0x48032000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 2        </td><td> GPTimer3   </td><td> 0x48034000         </td><td> 53         </td><td> Not used         </td></tr>",
   "<tr><td> 3        </td><td> GPTimer4   </td><td> 0x48036000         </td><td> 54         </td><td> Not used         </td></tr>",
   "<tr><td> 4        </td><td> GPTimer5   </td><td> 0x48820000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 5        </td><td> GPTimer6   </td><td> 0x48822000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 6        </td><td> GPTimer7   </td><td> 0x48824000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 7        </td><td> GPTimer8   </td><td> 0x48826000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 8        </td><td> GPTimer9   </td><td> 0x4803e000         </td><td> 55         </td><td> Not used         </td></tr>",
   "<tr><td> 9        </td><td> GPTimer10   </td><td> 0x48086000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 10        </td><td> GPTimer11   </td><td> 0x48088000         </td><td> 56         </td><td> Not used         </td></tr>",
   "<tr><td> 11        </td><td> GPTimer12   </td><td> 0x4ae20000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 12        </td><td> GPTimer13   </td><td> 0x48828000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 13        </td><td> GPTimer14   </td><td> 0x4882a000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 14        </td><td> GPTimer15   </td><td> 0x4882c000         </td><td> -1         </td><td> Not used         </td></tr>",
   "<tr><td> 15        </td><td> GPTimer16   </td><td> 0x4882e000         </td><td> -1         </td><td> Not used         </td></tr>",
 "</table>",
"<!-- -->"
);

// gen below code only 1 time
while (m_count < m_items.length) {
    document.write(m_items[m_count]);
    m_count++;
}